### ISSUE TITLE
Can we drop the node engine check

### ISSUE THREAD

**Issue by gulewei** [dcangulo/react-native-outside-press#326]
When I install this package, it complains incompatible node version.
```bash
error react-native-outside-press@1.2.1: The engine "node" is incompatible with this module. Expected version ">= 16.0.0". Got "14.21.3"
```
I don't think this is necessary, cause we don't run these code on node. So can we drop the engine check?

**Comment by dcangulo** [comment]
Yes, I think so. If you could create a PR for it, I'll try to merge and release it ASAP.
